In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

In [3]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(a[0][1])

2


In [5]:
print(a[1][2])

6


In [6]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [9]:
b = np.array([0,1,2,3,4,5])

In [10]:
b.mean()

2.5

In [11]:
b.std()

1.707825127659933

In [12]:
b.max()

5

In [ ]:
I = [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
print(i)